@VoterManagement_HostAddress = http://localhost:5016

GET {{VoterManagement_HostAddress}}/todos/
Accept: application/json

###

GET {{VoterManagement_HostAddress}}/todos/1
Accept: application/json

###
